ifndef AOLSERVER
    AOLSERVER  = /usr/local/aol/
endif

#
# Module name
#
MOD      =  nsmemcache.so

#
# Objects to build.
#
OBJS     = nsmemcache.o

include  $(AOLSERVER)/include/Makefile.module
